title: Spline
url: https://absaoss.github.io
keywords: apache spark, spark, dataframe, sql, structured streaming, data lineage, data provenance, tracking, big data, scala, cluster
baseurl: /spline
future: true
spline:
  version: 0.3.9
theme: jekyll-theme-slate

plugins:
  - jekyll-feed
  - jekyll-sitemap
